### ISSUE TITLE
A code change to reduce RAM footprint (also speed-up)

### ISSUE THREAD

**Issue by bewantbe** [trentool/TRENTOOL3#16]
I found that the transfer entropy functions in your toolbox consume a lot of RAM for long data (>1e5), I mean a hundred gigabyte or more.

Trace down to TEC_dsvalues.m and range_search.cpp, the code requiring some unused variable like "neighbors_p21_2":
   [ncount_p21_2,  neighbors_p21_2]  = range_search(...)
Actually the code range_search.cpp treat "count only" case specially
   neighbors_p21_2  = range_search(...)
which avoids Matlab's mysterious memory management (about the cell array).

Function TEC_dsvalues_noSourceEmb.m has the same problem.

Best wishes~

**Comment by mwibral** [comment]
Thanks,

this looks like a promising improvement.

Michael

**Comment by pwollstadt** [comment]
@bewantbe Thank you for the suggestion, I removed the unnecessary output variables in both functions `TEC_dsvalues.m` and `TEC_dsvalues_noSourceEmb.m`.
