### ISSUE TITLE
Example data ('exampledata/') are missing from the current version

### ISSUE THREAD

**Issue by Tambah** [trentool/TRENTOOL3#18]
I'm not sure whether to count that as an issue, but the exampledata folder is missing from the current version. Is it just moved elsewhere?

**Comment by pwollstadt** [comment]
Hi @Tambah, the folder has moved and now has its own repository [here](https://github.com/trentool/TRENTOOL3_exampledata).

**Comment by ernavk** [comment]
Would you consider updating the "TRENTOOL_doc" user documentation to reflect this change?
