### ISSUE TITLE
cao.m is missing

### ISSUE THREAD

**Issue by DarcyZhuoLiu** [trentool/TRENTOOL3#23]
There is no file called 'cao.m' in TRENTOOL. Consequently, when choosing 'cao' as the optimization algorithm to find optimal embedding parameter, the program is crushed.
If possible, I hope you can supplement this file.
Thank you very much~~~ @trentool @mwibral

**Comment by trentool** [comment]
Hi @DarcyZhuoLiu the Cao criterion for embedding is deprecated. Please use the Ragwitz method instead. We will remove this option from the documentation. Thanks!
