### ISSUE TITLE
tstool nn_prepare.mexmaci64 "Library not found"

### ISSUE THREAD

**Issue by phullett** [trentool/TRENTOOL3#31]
Would it be possible to provide the original nn_prepare.c, nn_search.c, and range_search.c files used to make the mex files for 64bit Mac (I cannot find these files on TSTOOL downloads and they did not come with TRENTOOL; only the mex files are provided). The current mex file for nn_prepare returns the following error (below). I think it is because mex file compatibility is sometimes an  issue across platforms and across Matlab versions unless the the mex file is generated locally. 

"Invalid MEX-file '/Users/pcnn/Documents/MATLAB/work2/TRENTOOL3-master/tstool_functions/mex_mac/mex64/nn_prepare.mexmaci64':
dlopen(/Users/pcnn/Documents/MATLAB/work2/TRENTOOL3-master/tstool_functions/mex_mac/mex64/nn_prepare.mexmaci64, 6): Library not loaded:
@loader_path/libmex.dylib
  Referenced from: /Users/pcnn/Documents/MATLAB/work2/TRENTOOL3-master/tstool_functions/mex_mac/mex64/nn_prepare.mexmaci64
  Reason: image not found."

Thanks!

**Comment by mwibral** [comment]
Dear Phullet,

I fear that those source files are from the TSTool project. At the 
moment we only have those mex files. However, you may have to look for 
Fortran instead of c-files, if I remember correctly.

Best,

Michael

Btw: If you're familiar with python, you may also want to have a look at 
IDtxl (https://github.com/pwollstadt/IDTxl) , TRENTOOL's successor 
(removes the eed for MATLAb licenses).

**Comment by phullett** [comment]
Thank you for the quick reply! They are from the TSTool project-- I will likely use IDtxl tool instead. Also, thank you for this TE resource!

Best,

Patrick

**Comment by pwollstadt** [comment]
Hi all, I will close this issue. Feel free to reopen if necessary.

**Comment by fra1800** [comment]
Hi all, when I run the code on matlab it gives me the following error:
Invalid MEX-file
'/Users/francescatancredi/Documents/MATLAB/TRENTOOL3-master/tstool_functions/mex_mac/mex64/nn_prepare.mexmaci64':
dlopen(/Users/francescatancredi/Documents/MATLAB/TRENTOOL3-master/tstool_functions/mex_mac/mex64/nn_prepare.mexmaci64,
0x0006): Library not loaded: @loader_path/libmat.dylib
Referenced from: <04E03B10-32AF-4711-B7B8-E3EBD7B64DC1>
/Users/francescatancredi/Documents/MATLAB/TRENTOOL3-master/tstool_functions/mex_mac/mex64/nn_prepare.mexmaci64
Reason: tried:
'/Users/francescatancredi/Documents/MATLAB/TRENTOOL3-master/tstool_functions/mex_mac/mex64/libmat.dylib'
(no such file), '/usr/local/lib/libmat.dylib' (no such file), '/usr/lib/libmat.dylib' (no
such file, not in dyld cache)

Could anyone help me solve the problem?
