### ISSUE TITLE
 less than mininmum nr of trials reached ACT threshold criteria - to solve the problem change the ACT threshold (cfg.actthrvalue) or remove the bad channel combinations

### ISSUE THREAD

**Issue by keshavbk** [trentool/TRENTOOL3#32]
Hi,

I am receiving the above error.

I am an undergrad, very new to the world of computational neuroscience. I am happy to provide any other necessary information, but I'm not sure what is necessary. I am also unsure about what a bad channel combination is in the first place, so it would be great if anyone could explain that as well.

Thanks,

Keshav Kundassery
Vanderbilt University
BIEN Lab

**Comment by pwollstadt** [comment]
Hi Keshav, this means that you have too many trials with a autocorrelation decay time above the threshold set in cfg.actthrvalue. These trials get excluded from the analysis. A bad channel combination is a channel pair where the number of trials for at least one channel is too low. You may want to consider changing the actthrvalue to get more trials included. 
If you are happy with working in Python, you may also want to have a look at our new toolbox [IDTxl](https://github.com/pwollstadt/IDTxl). The embedding used there does not rely on the ACT for the calculation of the embedding parameters.

**Comment by pwollstadt** [comment]
P.S.: Since this is not an error in the code, I will close this issue. Feel free to send me an email if you have more questions or open another issue if you encounter a bug.
