### ISSUE TITLE
Mutual information between two variables

### ISSUE THREAD

**Issue by asadmalik85** [trentool/TRENTOOL3#35]
Hi, is there a quick way for me to get the mutual information between two variables (e.g. time-series)? Thanks.

**Comment by pwollstadt** [comment]
Hi, we are no longer maintaining TRENTOOL, but other packages offer quick ways to compute an MI. I recommend either [IDTxl](https://github.com/pwollstadt/IDTxl), [JIDT](https://github.com/jlizier/jidt), or just [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.mutual_info_regression.html). IDTxl is TRENTOOL's follow-up project, written in Python (as is scikit), JIDT is written in Java but offers wrappers for Matlab/Octave and Python.
