### ISSUE TITLE
number of permutations

### ISSUE THREAD

**Issue by DiBeck** [trentool/TRENTOOL3#5]
Dear all, 

i hope you can help me with an issue. My college and me a working on the estimation of Transferentropy in neuronal networks. I am new in the lab and installed a fresh Trentool version 3.3.2. And took the script from my college, which works fine with her version and tried to use it with my version. 

First i received the error that 

```
cfgTEP.predicttime_u
```

does not exist. I changed the  

```
cfgTEP.predictiontime_u* to *cfgTEP.predicttime_u
```

Now i receiving the error that the number of permutations is either to hugh or to small, whatever value i choose. Did anybody ran into this problem before? What is it i am doing wrong? I appreciate your help. 

```
Check data and config
par state is 0

 - ok
Building channelpairs
Select channels - ok
Read data
time indices are 1 and 299

 - ok
Calculate ACT [-] - ok
Select trials - ok
Calculate optimization with Ragwitz criterion

------------------------------------------------------------
Optimal tau for this dataset may be: 0.2

Optimal dimension for this dataset may be: 10
 - ok

add TEprepare structure to original data structure  - ok
done

Check data and config - ok

Checking number of permutations
Error using TEsurrogatestats (line 515)
TRENTOOL ERROR: cfg.numpermutation too huge!

Error in TE_Auswertung (line 191)
TEpermtest=TEsurrogatestats(cfgTESS,data_prepared);
```

Thanks Dirk

**Comment by pwollstadt** [comment]
Hi Dirk,

TRENTOOL throws an error if the number of computations is too big in relation to the number of trials you are using. I checked the code and there seem to be cases, where it is not possible to set a correct number of permutations, I will fix this. However, it seems like you have very little trials left for analysis in one of your signal combinations. You should check that and make sure that the number of trials is sufficient to do permutation testing.

Best, Patricia

**Comment by DiBeck** [comment]
Thanks for the help! In the moment I use a data set with reduced size and that might be the problem. 

kind regards Dirk

**Comment by pwollstadt** [comment]
Hi Dirk,

as a workaround, you can just leave the field 

```
cfgTEP.numpermutation
```

undefined and TRENTOOL will set an appropriate default value. This does not guarantee that your statistics make sense, i.e., you have to check yourself if you have enough trials left (~ 15 or more per channel combination) for a meaningful permutation test.
We are working on some checks that will issue a warning/throw an error if the number of trials is too low.

Best regards,
Patricia

**Comment by trentool** [comment]
@DiBeck we included a new function [`TEchecknumperm.m`](https://github.com/trentool/TRENTOOL3/blob/master/private/TEchecknumperm.m), which depending on whether the user provided a number of permutations
1. checks the provided number of permutations, or 
2. sets the number of permutations based on the requested alpha level and units of observations.
