### ISSUE TITLE
Data for the examples

### ISSUE THREAD

**Issue by DiBeck** [trentool/TRENTOOL3#6]
Hello, 

this is not an urgent comment. However i tried to use the `example_script_cpu.m` but the data is not available in github. It would be nice if there is a working example. 

Thanks!

**Comment by pwollstadt** [comment]
Hi Dirk,
data sets for the example scripts are in a different branch:

https://github.com/trentool/TRENTOOL3/tree/exampledata

Maybe keeping the data as a different branch is a bit confusing, I might change that in the future.

Have a nice day,

Patricia

P.S.: See also this wiki page on the example data: https://github.com/trentool/TRENTOOL3/wiki/Example-data-sets

**Comment by DiBeck** [comment]
Thanks, that was my fault. I did not understood the github branches. 

Kind regards 

Dirk
