### ISSUE TITLE
example_script_CPUmethod.m error

### ISSUE THREAD

**Issue by dwuab** [trentool/TRENTOOL3#7]
I ran `example_script_CPUmethod.m` on Matlab2014a (Mac OS 10.10.3) with `fieldtrip-20150601` and got the following error:

```
Checking number of permutationsOperands to the || and && operators must be convertible to logical scalar values.

Error in TEsurrogatestats (line 515)
    elseif nrtrials>31 && cfg.numpermutation > 2^31


Error in InteractionDelayReconstruction_calculate (line 103)
    TGA_results=TEsurrogatestats(cfgTESS,dataprep);

Error in example_script_CPUmethod (line 67)
TGA_results = InteractionDelayReconstruction_calculate(cfgTEP,cfgTESS,data);
```

with a little bit of debugging, I found that `nrtrials` was a a vector with two elements `[150 150]` and `cfg.numpermutation` was 50000.

**Comment by trentool** [comment]
That is right, the function should use the maximum over the vector `ntrials`. I fixed this, thank you for pointing this out.

Best,
Patricia
